### ISSUE TITLE
Pictures from galleries are not named in order

### ISSUE THREAD

**Issue by Ganymede23** [Jackhammer9/RedDownloader#47]
Hello! I was testing this and tried downloading a couple submissions with galleries and found that they're not named/downloaded in order:

- Example 1: https://www.reddit.com/r/announcements/comments/hrrh23/now_you_can_make_posts_with_multiple_images/
This case was downloaded in this order (1, 3, 2)
To be clear, this means that the pictured named 'download2.jpeg' is actually the number 3 on the gallery and should be named 'download3.jpeg'. Same rule applies to the next examples.

- Example 2: https://www.reddit.com/r/dogelore/comments/jbu197/he_chose_poorly/
This case was downloaded in this order (6, 5, 1, 2, 7, 4, 8. 3)

- Example 3: https://www.reddit.com/r/ProCreate/comments/10wdd7c/gallery_post_description_in_the_comment/
This case was downloaded in this order (1, 5, 2, 9, 4, 3, 7, 8, 6)

I've tested it multiple times and the order repeats itself. Doesn't seem to be random.
It would be nice to have the files named in order, so it's easier to manage.

I hope this is helpful. Thank you!

**Comment by Jackhammer9** [comment]
Greetings,

Thank you for bringing this to my attention, i have gone through and it looked like reddit doesn't return pictures in order via API calls nonetheless  i am now sorting the media by their ids before downloading so that seems to be working fine.

I will be closing this issue but please don't hesitate to reopen if you should face any issue
